logging:
  level:
    org:
      springframework:
        transaction.interceptor: trace #Proxy ??
        jdbc.datasource.DataSourceTransactionManager: debug
        # JPA Log
        orm.jpa.JpaTransactionManager: debug
      hibernate:
        SQL: debug
        resource.transaction: debug
