logging:
  level:
    org:
      springframework:
        transaction.interceptor: trace #Proxy ??
        jdbc.datasource.DataSourceTransactionManager: debug
        orm.jpa.JpaTransactionManager: debug # JPA Log
      hibernate:
        SQL: debug
        resource.transaction: debug
